#!/usr/bin/env node

process.on("unhandledRejection", (error) => {
  console.error(error)
  process.exit(1)
})

const { run, test, expect, snapshot, info } = require("@xieyuheng/test-runner")
const changeCase = require("change-case")
const path = require("path")
const fs = require("fs")

let commands = {}

commands.t = async () => {
  await commands.test_all()
}

commands.test_all = async () => {
  await commands.test_lib()
  await commands.test_snapshot()
  await commands.test_exp()
}

commands.test_lib = async () => {
  await test("node $file", { file: "lib/**/*.test.js" }, expect.ok)
}

commands.test_snapshot = async () => {
  await test(
    "node $file",
    { file: "lib/**/*.snapshot.js" },
    snapshot.out(({ file }) =>
      path.resolve("snapshot", changeCase.paramCase(file) + ".out")
    )
  )
}

commands.test_exp = async () => {
  await test(
    "./bin/exp.js run --no-module $file",
    { file: "tests/**/**.test.exp" },
    expect.ok
  )

  await test(
    "./bin/exp.js run --no-module $file",
    { file: "tests/**/**.snapshot.exp" },
    snapshot.out(({ file }) => file + ".out")
  )

  await test(
    "./bin/exp.js run --no-module $file",
    { file: "tests/**/**.error.exp" },
    snapshot.err(({ file }) => file + ".out")
  )
}

info()

run(commands)
